# Generated by Django 4.2.4 on 2023-08-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=20)),
                ('demanda', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AreaProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('serialNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('generacion', models.IntegerField()),
                ('PArea', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=10)),
                ('vCliente', models.CharField(max_length=40)),
                ('telf', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=40)),
                ('contrasenia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vSerialNumber', models.CharField(max_length=20)),
                ('total', models.FloatField()),
                ('ci', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
