# Generated by Django 4.2.3 on 2023-08-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0002_alter_producto_options_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='vCliente',
        ),
    ]
