# Generated by Django 4.2.4 on 2023-08-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0003_remove_usuario_vcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
    ]
