# Generated by Django 4.2.4 on 2023-08-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0004_remove_venta_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ci',
        ),
    ]
